### PR TITLE
Search for Civ3 Folder in Steam Folder on Linux/Mac

### LINKED ISSUE #385: Crash on Launch on M1 Mac
Resolve the following, and log something useful instead of crashing:

```
E 0:00:01.586   void System.IO.FileSystem.CreateDirectory(System.String ): System.TypeInitializationException: The type initializer for 'Util' threw an exception. ---> System.IO.IOException: Read-only file system
  <C++ Error>   Unhandled exception
  <C++ Source>  :0 @ void System.IO.FileSystem.CreateDirectory(System.String )()
  <Stack Trace> :0 @ void System.IO.FileSystem.CreateDirectory(System.String )()
                :0 @ System.IO.DirectoryInfo System.IO.Directory.CreateDirectory(System.String )()
                :0 @ Microsoft.Win32.KeyHandler..ctor(Microsoft.Win32.RegistryKey , System.String , Boolean )()
                :0 @ Microsoft.Win32.KeyHandler..ctor(Microsoft.Win32.RegistryKey , System.String )()
                :0 @ Microsoft.Win32.KeyHandler Microsoft.Win32.KeyHandler.Lookup(Microsoft.Win32.RegistryKey , Boolean )()
                :0 @ Microsoft.Win32.RegistryKey Microsoft.Win32.UnixRegistryApi.OpenSubKey(Microsoft.Win32.RegistryKey , System.String , Boolean )()
                :0 @ Microsoft.Win32.RegistryKey Microsoft.Win32.RegistryKey.OpenSubKey(System.String , Boolean )()
                :0 @ ()
                :0 @ Microsoft.Win32.RegistryKey Microsoft.Win32.Registry.ToKey(System.String , Boolean )()
                :0 @ System.Object Microsoft.Win32.Registry.GetValue(System.String , System.String , System.Object )()
                Util.cs:49 @ System.String Util.Civ3PathFromRegistry()()
                Util.cs:38 @ System.String Util.GetCiv3Path()()
                Util.cs:10 @ Util..cctor()()
                :0 @ --- End of inner exception stack trace ---()
                MainMenuMusicPlayer.cs:19 @ void MainMenuMusicPlayer._Ready()()
```

### PR DESCRIPTION
**Pull request by pcen**
- tested on mac
- cannot currently test on linux
- whitespace dif from running formatter on Utils.cs based on .editorconfig
- prevents Godot from crashing like in https://github.com/C7-Game/Prototype/issues/385 by not attempting to read from windows registry when not running on windows

### CODE REVIEW

File: C7/Util.cs [hunk 1]
```diff
@@ -5,48 +5,65 @@
...
+		if (path != null) { return path; }
+
+		if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) {
+			// Look up in Windows registry if present
+			path = Civ3PathFromRegistry();
+			if (path != null) { return path; }
+		} else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX) || RuntimeInformation.IsOSPlatform(OSPlatform.Linux)) {
+			// Check for a civ3 folder in steamapps/common
+			// TODO: should this method only be used at dev time?
+			var root = new System.IO.DirectoryInfo(Util.SteamCommonDir());
```
Comment (QuintillusCFC) [inline C7/Util.cs]: Minor: We're trying out best to always specify the type, to make it easier to read going forward (in this case that would be DirectoryInfo).

My thought would be we should leave this check on all the time as it will make it convenient for new users.

**Review by QuintillusCFC — APPROVED** [review]
Approving from a Windows testing standpoint.  One minor comment but no need to re-review.
