### PR TITLE
320 - Fix the overloaded NeighborsWater method.

### LINKED ISSUE #320: Disambiguate Overloaded NeighborsWater Method in Tile.cs
Our NeighborsWater method is currently used for two different purposes, which should have two different logical evaluations, and which quite reasonably both think it is the method they should be calling.  This is mostly on me as I added the first iteration of it, which focused purely on map graphics needs but gave it a name that was very inviting for other purposes.

As a result, right now, it looks like this:

```
foreach (Tile neighbor in getDiagonalNeighbors()) {
//check for whether it's a water tile
```

Aside from questions about whether you consider the "diagonal" tiles to be the ones that share edges or vertices (currently in the code, it means the ones that share edges), the thing that should raise eyebrows is why doesn't it check all the neighboring tiles?  For important questions such as, "can a tile on this city build naval units?", we want to check all neighboring tiles.

The reason it's written the way it is currently is that for the question, "do we want to display large forest/jungle/marsh graphics, or small ones?", the relevant question is "do the neighbors that share an edge with this tile contain water?  if so, use small graphics."  The method was written with this definition of neighboring water in mind, and got picked up for everything else.

So in essence this is a classic equivalent of when you get corruption in your database because one part of the business uses Term A and means one thing, and another part of the business uses Term A and means something else, and IT doesn't realize that Term A can mean two different things, and re-uses the same field.  Like in most of those cases, there were also a few months between the first use of NeighborsWater and the subsequent uses of it, so there was time to forget exactly what it meant in the first place.

I suggest we use the "_any_ neighboring tile is a water tile" definition for NeighborsWater, and have the graphics uses cases use the getDiagonalNeighbors method and LINQ to figure out what they need.  They're the specialized case here.

This is also a bug because if you found a city that only borders water via vertices, it cannot build Galleys; the same applies for barbarian camps that only neighbor water via vertices.

### PR DESCRIPTION
**Pull request by QuintillusCFC**
This fixes the bug where cities/barb camps that were connected to water only along a vertex could not build water units.

Closes #320

### CODE REVIEW

File: C7GameData/Tile.cs [hunk 1]
```diff
@@ -79,17 +79,22 @@ public Tile()
 		//Sometimes we care *specifically* about the Coast terrain, e.g. galleys can only move on that terrain, not Sea or Ocean
 		//Those cases should not use this method.
 		public bool NeighborsWater() {
-			foreach (Tile neighbor in getDiagonalNeighbors()) {
+			foreach (Tile neighbor in neighbors.Values) {
```
Comment (WildWeazel) [inline C7GameData/Tile.cs:82]: Remember that cities are a special case for diagonal neighbors. Otherwise a diagonal water neighbor only is not considered connected, ie the land connection takes priority. Is this taken into account when there is no city?

Comment (QuintillusCFC) [reply C7GameData/Tile.cs:82]: Do you mean in terms of trade connections?  I guess I'm not sure exactly what case it is you mean where a diagonal (vertex) neighbor doesn't count for water, other than the graphics case mentioned in the comment.

So far this is only used when deciding what a city can build, whether a barbarian camp spawns boats, and how appealing a city site is to the AI.

Comment (WildWeazel) [reply C7GameData/Tile.cs:82]: If you have water tiles at N/S and land tiles at E/W, that's an isthmus and sea units can't move between the water tiles. But if N is a city, sea units can move in and out of it. I just want to be sure this method isn't a general case for finding connected water tiles.

Comment (QuintillusCFC) [reply C7GameData/Tile.cs:82]: Ohhhh, right!  Forgot about that.  Well, the isthmus case _is_ a problem, but it doesn't use this method.  For both barbarian and non-barbarian AIs, the `GetCoastNeighbors` method in `Tile.cs` is used, which doesn't check for isthmuses.  I'm not sure off the top of my head for human moves.  But I have seen AI galleys move across isthmuses.

I don't think this method could be easily misused for that, as it returns a boolean, and our movement/pathing methods are looking for tile objects that can be moved to.  I.e. this method doesn't tell you which neighboring tiles are water, so you can't use it to decide where to move.

Nonetheless, that is a good catch, I wrote it up as #369 .  I'd probably do it after #148 , which I see as the next iteration in improving the accuracy of movement possibilities.

**Review by WildWeazel — APPROVED** [review]
